services:
  - docker

install:
  - echo "no installs"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t "$DOCKER_USERNAME"/quiz-app-image-upload . # build the docker image

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker hub
  - docker push "$DOCKER_USERNAME"/quiz-app-image-upload # push the image to docker hub
