apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: quiz-app-reverse-proxy
  name: quiz-app-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: quiz-app-reverse-proxy
  template:
    metadata:
      labels:
        service: quiz-app-reverse-proxy
    spec:
      containers:
        - image: noyan09/quiz-app-reverse-proxy
          name: quiz-app-reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
      restartPolicy: Always
