apiVersion: v1
kind: Service
metadata:
  labels:
    service: quiz-app-reverse-proxy
  name: quiz-app-reverse-proxy-svc
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    service: quiz-app-reverse-proxy
  type: LoadBalancer
